.eslintignore
.eslintrc.js
.gitignore
package-lock.json
package.json

add eslint for typescript (#37)

---

contracts/components/BaseComponent.sol
contracts/components/IBaseComponent.sol
test_forge/TestDistribution.t.sol

Implement setWallet on BaseComponent

---

contracts/instance/IInstanceService.sol
contracts/instance/Instance.sol
contracts/instance/InstanceService.sol
test_forge/base/TestGifBase.sol
test_forge/instance/TestInstanceService.t .sol

implement setMasterInstanceReader (#194)

---

contracts/components/BaseComponent.sol
contracts/components/Distribution.sol
contracts/components/IBaseComponent.sol
contracts/components/Pool.sol
contracts/components/Product.sol
contracts/instance/IInstanceService.sol
contracts/instance/InstanceAccessManager.sol
contracts/instance/InstanceService.sol
contracts/instance/base/ComponentServiceBase.sol
contracts/instance/module/IAccess.sol
contracts/instance/service/DistributionService.sol
contracts/instance/service/PoolService.sol
contracts/instance/service/ProductService.sol
test_forge/TestDistribution.t.sol
test_forge/TestPool.t.sol
test_forge/TestProduct.t.sol
test_forge/base/TestGifBase.sol
test_forge/instance/TestInstanceAccessManager.t.sol
test_forge/instance/service/TestDistributionService.t.sol
test_forge/instance/service/TestPoolService.t.sol
test_forge/instance/service/TestProductService.t.sol
test_forge/mock/SimpleDistribution.sol
test_forge/mock/SimplePool.sol
test_forge/mock/SimpleProduct.sol

component lock/unlock (#190)

---

contracts/components/Product.sol
contracts/instance/service/BundleService.sol
contracts/instance/service/IBundleService.sol
contracts/instance/service/IPolicyService.sol
contracts/instance/service/PolicyService.sol
test_forge/TestProduct.t.sol
test_forge/mock/SimpleProduct.sol

implement collectPremium (#178)

---

contracts/instance/InstanceAccessManager.sol
contracts/instance/module/IAccess.sol
test_forge/instance/TestInstanceAccessManager.t.sol

component with custom role (#203)

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/zsh/aliases.zsh
.gitignore
contracts/components/Distribution.sol
contracts/components/IDistributionComponent.sol
contracts/instance/InstanceService.sol
contracts/instance/module/ISetup.sol
contracts/instance/service/DistributionService.sol
contracts/instance/service/IDistributionService.sol
contracts/instance/service/IPolicyService.sol
contracts/instance/service/PolicyService.sol
contracts/types/Referral.sol
docs_manual/application.md
docs_manual/distribution.md
docs_manual/distribution_fee.drawio
test_forge/TestProduct.t.sol
test_forge/components/distribution/Referral.t.sol

move and track distribution related tokens during underwriting (#240)

---

.github/workflows/docgen.yml
.gitignore
contracts/components/README.adoc
contracts/instance/README.adoc
docs/antora.yml
docs/config.js
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/api/nav.adoc
docs/templates/contract.hbs
docs/templates/helpers.js
docs/templates/page.hbs
docs/templates/properties.js
hardhat.config.ts

generated documentation (#263)

---

contracts/instance/service/BundleService.sol
contracts/instance/service/IBundleService.sol
contracts/instance/service/IPolicyService.sol
contracts/instance/service/IPoolService.sol
contracts/instance/service/PolicyService.sol
contracts/instance/service/PoolService.sol
contracts/types/Amount.sol
scripts/libs/services.ts
test_forge/TestProduct.t.sol

move and track pool and bundle fees (#280)

---

.gitignore
README.md
package-lock.json
package.json
scripts/libs/deployment.ts
scripts/libs/deployment_state.ts
scripts/libs/libraries.ts
scripts/libs/registry.ts
scripts/libs/services.ts
scripts/libs/transaction.ts
scripts/libs/verification.ts
scripts/libs/verification_log.ts
scripts/libs/verification_queue.ts
scripts/verify_deployment.ts

Script to verify deployment

---

test/instance/TestInstanceService.t.sol

add test for roles (#388)

---

contracts/instance/IInstanceService.sol
contracts/instance/InstanceService.sol
docs/modules/ROOT/pages/arch.adoc
docs_manual/instance.md
scripts/libs/instance.ts
scripts/new_instance.ts
test/base/GifTest.sol
test/instance/TestInstanceService.t.sol

refactor: rename createInstanceClone to createInstance (closes #440)

---

contracts/distribution/DistributionService.sol
contracts/distribution/IDistributionComponent.sol
contracts/distribution/IDistributionService.sol
contracts/pool/BasicPoolAuthorization.sol
contracts/pool/BundleService.sol
contracts/pool/IBundleService.sol
contracts/pool/IPoolComponent.sol
contracts/pool/Pool.sol
contracts/pool/PoolService.sol
contracts/product/ClaimService.sol
contracts/product/PolicyService.sol
contracts/shared/ComponentService.sol
contracts/staking/Staking.sol
contracts/type/Amount.sol
contracts/type/Referral.sol
contracts/type/UFixed.sol
test/TestFees.t.sol
test/type/UFixed.t.sol

bundle fee withdrawal (#419)

---

contracts/product/BasicProduct.sol
contracts/product/IPolicyService.sol
contracts/product/PolicyService.sol
contracts/product/Product.sol
test/TestProduct.t.sol
test/mock/SimpleProduct.sol

implenent decline policy (#441)

---

contracts/product/IPolicyService.sol
contracts/product/PolicyService.sol
contracts/product/Product.sol
contracts/type/Timestamp.sol
test/TestProduct.t.sol
test/mock/SimpleProduct.sol

implement expire policy (#441)

---

.vscode/settings.json
contracts/instance/module/IComponents.sol
contracts/pool/BasicPool.sol
contracts/pool/BasicPoolAuthorization.sol
contracts/pool/IPoolService.sol
contracts/pool/Pool.sol
contracts/pool/PoolService.sol
test/TestBundle.t.sol
test/TestPool.t.sol

Rename maxCapitalAmount to maxBalanceAmount in pool contracts (#476)

---

contracts/distribution/DistributionService.sol
contracts/distribution/IDistributionService.sol
contracts/pool/BundleService.sol
contracts/pool/IBundleService.sol
contracts/pool/IPoolService.sol
contracts/pool/PoolService.sol
contracts/product/ClaimService.sol
contracts/product/PolicyService.sol
contracts/shared/ComponentService.sol
contracts/shared/TokenTransferLib.sol
test/TestBundle.t.sol
test/TestFees.t.sol

centralization of token collection (#471)

---

.vscode/settings.json
contracts/authorization/Authorization.sol
contracts/instance/InstanceAdmin.sol
contracts/instance/InstanceService.sol
contracts/pool/IBundleService.sol
contracts/product/PolicyService.sol
contracts/registry/RegistryAdmin.sol
contracts/shared/ComponentService.sol
contracts/shared/TokenHandler.sol
contracts/shared/TokenHandlerDeployerLib.sol
contracts/staking/Staking.sol
scripts/libs/libraries.ts
scripts/libs/registry.ts
scripts/libs/services.ts
test/shared/TokenHandler.t.sol

TokenHandler access protection 

---

contracts/staking/IStaking.sol
contracts/staking/TargetManagerLib.sol
contracts/type/Seconds.sol
test/staking/Staking.t.sol

enforce minimum staking duration (#510)

---

contracts/staking/IStaking.sol
contracts/staking/StakeManagerLib.sol
contracts/staking/Staking.sol
test/staking/Staking.t.sol

check lockedUntil when unstaking (closes #536)

---

contracts/instance/InstanceAuthorizationV3.sol
contracts/instance/InstanceReader.sol
contracts/instance/InstanceStore.sol
contracts/instance/base/ObjectLifecycle.sol
contracts/instance/module/IPolicy.sol
contracts/product/ApplicationService.sol
contracts/product/IPolicyService.sol
contracts/product/PolicyService.sol
contracts/type/StateId.sol
docs_manual/lifecycle.md
scripts/libs/services.ts
test/TestProduct.t.sol

add new lifecycle state PAID to premiuminfo (#535)

---

contracts/examples/fire/FireProduct.sol
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/example-fire.adoc
package-lock.json
package.json
scripts/deploy_all.ts
scripts/deploy_fire_components.ts
scripts/libs/verification_queue.ts

add deploy script for fire components (#502)

---

contracts/distribution/BasicDistribution.sol
contracts/distribution/Distribution.sol
contracts/distribution/DistributionService.sol
contracts/examples/fire/FireProduct.sol
contracts/oracle/OracleService.sol
contracts/pool/BasicPool.sol
contracts/pool/Pool.sol
contracts/product/PricingService.sol
contracts/product/Product.sol
contracts/registry/IRegistry.sol
contracts/registry/Registry.sol
contracts/shared/Component.sol
contracts/shared/ComponentVerifyingService.sol
contracts/shared/IComponent.sol
contracts/shared/INftOwnable.sol
contracts/shared/NftOwnable.sol
contracts/staking/IStakingService.sol
contracts/staking/StakingService.sol
test/examples/fire/FireProductClaims.t.sol

validate nft type (#512)

---

contracts/distribution/DistributionService.sol
contracts/examples/fire/FireProduct.sol
contracts/instance/InstanceService.sol
contracts/pool/BundleService.sol
contracts/pool/PoolService.sol
contracts/product/ApplicationService.sol
contracts/product/ClaimService.sol
contracts/product/PolicyService.sol
contracts/product/PricingService.sol
contracts/shared/ComponentService.sol
contracts/shared/NftOwnable.sol
contracts/staking/StakingService.sol

nft type validation (#512)

---

contracts/distribution/DistributionService.sol

input validation (#518)

---

contracts/distribution/BasicDistribution.sol
contracts/distribution/BasicDistributionAuthorization.sol
contracts/distribution/Distribution.sol
contracts/distribution/DistributionService.sol
contracts/distribution/IDistributionService.sol
test/component/distribution/Distributor.t.sol

implement changeDistributorType (#584)

---

contracts/examples/unpermissioned/SimpleProduct.sol
contracts/instance/InstanceAuthorizationV3.sol
contracts/instance/base/ObjectLifecycle.sol
contracts/product/ClaimService.sol
contracts/product/IClaimService.sol
contracts/product/Product.sol
docs_manual/lifecycle.md
test/component/product/ProductClaim.t.sol
test/component/product/ProductPayout.t.sol

Add CANCELLED state to payout lifecycle (#587)

---

contracts/distribution/DistributionService.sol
contracts/examples/fire/FireProduct.sol
contracts/examples/unpermissioned/SimpleProduct.sol
contracts/instance/InstanceAuthorizationV3.sol
contracts/instance/InstanceReader.sol
contracts/instance/InstanceStore.sol
contracts/instance/base/ObjectLifecycle.sol
contracts/instance/module/IComponents.sol
contracts/pool/PoolService.sol
contracts/product/BasicProduct.sol
contracts/product/ClaimService.sol
contracts/product/IProductComponent.sol
contracts/product/PricingService.sol
contracts/product/Product.sol
contracts/shared/ComponentService.sol
contracts/type/ObjectType.sol
test/TestDistribution.t.sol
test/TestPool.t.sol
test/TestProduct.t.sol
test/base/GifTest.sol
test/component/pool/PoolRegistration.t.sol
test/component/product/ProductRegistration.t.sol
test/examples/composeability/ProductWithReinsurance.sol
test/examples/composeability/ProductWithReinsurance.t.sol
test/examples/external/ExternallyManagedPool.t.sol
test/examples/external/ExternallyManagedProduct.sol
test/examples/verifying/VerifyingPool.t.sol
test/examples/verifying/VerifyingProduct.sol

add new ObjectType FeeInfo (#599)

---

scripts/libs/deployment.ts
scripts/libs/instance.ts

prepare accessmanager verification data during deployment (closes #615)

---

contracts/examples/unpermissioned/SimpleProduct.sol
contracts/product/IPolicyService.sol
contracts/product/PolicyService.sol
contracts/product/PolicyServiceLib.sol
contracts/product/Product.sol
scripts/libs/libraries.ts
scripts/libs/services.ts
test/TestProduct.t.sol

implenent adjustActivation (closes #532)

---

contracts/examples/fire/FireProduct.sol
contracts/examples/unpermissioned/SimpleProduct.sol
contracts/product/IRiskService.sol
contracts/product/Product.sol
contracts/product/RiskService.sol
contracts/type/RiskId.sol
scripts/libs/services.ts
test/TestBundle.t.sol
test/TestFees.t.sol
test/TestProduct.t.sol
test/base/GifClusterTest.sol
test/base/GifTest.sol
test/component/distribution/Referral.t.sol
test/component/product/ProductClaim.t.sol
test/component/product/ProductClusterRisk.t.sol
test/component/product/ProductLifecycle.t.sol
test/component/product/ProductPayout.t.sol
test/component/product/ProductRisk.t.sol
test/component/registration/ProductCluster.t.sol
test/examples/composeability/PoolWithReinsurance.sol
test/examples/composeability/ProductWithReinsurance.t.sol
test/examples/external/ExternallyManagedProduct.sol
test/examples/verifying/VerifyingProduct.sol
test/instance/service/TestPricingService.t.sol
test/release/component/ReleaseProduct.t.sol
test/staking/TvlCalculation.t.sol
test/type/RiskId.t.sol

refactor RiskId creation to include product nftid in the riskid (#621)

---

contracts/staking/IStaking.sol
contracts/staking/IStakingService.sol
contracts/staking/README.adoc
contracts/staking/StakeManagerLib.sol
contracts/staking/Staking.sol
contracts/staking/StakingLib.sol
contracts/staking/StakingReader.sol
contracts/staking/StakingService.sol
scripts/libs/libraries.ts
scripts/libs/registry.ts
test/staking/RewardCalculation.t.sol
test/staking/Staking.t.sol
test/staking/StakingRateManagement.t.sol
test/staking/StakingSetup.t.sol
test/staking/TargetManagement.t.sol
test/staking/TvlCalculation.t.sol

implement restaking (#591)

---

contracts/instance/IInstance.sol
contracts/instance/IInstanceService.sol
contracts/instance/Instance.sol
contracts/instance/InstanceService.sol
contracts/shared/ComponentService.sol
docs/modules/ROOT/pages/example-fire.adoc
scripts/libs/instance.ts
test/base/GifTest.sol
test/component/product/ProductRegistration.t.sol
test/release/ReleaseInstance.t.sol
test/staking/Staking.t.sol

allow creation of instances with token registry disabled (#646)

---

contracts/instance/base/BalanceStore.sol

Remove redundant isRegistered mapping in BalanceStore.sol (closes #661)

---

contracts/staking/Staking.sol
contracts/staking/StakingStore.sol
scripts/libs/registry.ts
test/staking/Staking.t.sol
test/staking/StakingSetup.t.sol

add tests for staking

---

README.md
hardhat.config.ts
package-lock.json
scripts/deploy_dip.ts
scripts/libs/registry.ts

deploy with existing dip (#704)
